const B748H_LocalVariables = {
	IRS: {
		L: {
			STATE: 'L:B748H_IRS_L_STATE',
			SWITCH_STATE: 'L:B748H_IRS_L_SWITCH_STATE',
			INIT_TIME:  'L:B748H_IRS_L_INIT_TIME',
			TIME_FOR_ALIGN: 'L:B748H_IRS_L_TIME_FOR_ALIGN'
		},
		C: {
			STATE: 'L:B748H_IRS_C_STATE',
			SWITCH_STATE: 'L:B748H_IRS_C_SWITCH_STATE',
			INIT_TIME:  'L:B748H_IRS_C_INIT_TIME',
			TIME_FOR_ALIGN: 'L:B748H_IRS_C_TIME_FOR_ALIGN'
		},
		R: {
			STATE: 'L:B748H_IRS_R_STATE',
			SWITCH_STATE: 'L:B748H_IRS_R_SWITCH_STATE',
			INIT_TIME:  'L:B748H_IRS_R_INIT_TIME',
			TIME_FOR_ALIGN: 'L:B748H_IRS_R_TIME_FOR_ALIGN'
		},
		IS_INITED: 'L:B748H_IRS_IS_INITED',
		POSITION_SET: 'L:B748H_IRS_POSITION_SET'
	},
	VNAV: {
		CUSTOM_VNAV_CLIMB_ENABLED: 'L:B748H_VNAV_CUSTOM_CLIMB_ENABLED'
	},

	SIM_RATE_MANAGER: {
		ACTIVATED: 'L:B748H_SIM_RATE_MANAGER_ACTIVATED'
	}
}