const B748H_LocalVariables = {
	IRS: {
		L: {
			STATE: 'B748H_IRS_L_STATE',
			SWITCH_STATE: 'B748H_IRS_L_SWITCH_STATE'
		},
		C: {
			STATE: 'B748H_IRS_C_STATE',
			SWITCH_STATE: 'B748H_IRS_C_SWITCH_STATE'
		},
		R: {
			STATE: 'B748H_IRS_R_STATE',
			SWITCH_STATE: 'B748H_IRS_R_SWITCH_STATE'
		},
		IS_INITED: 'B748H_IRS_IS_INITED',
		POSITION_SET: 'B748H_IRS_POSITION_SET'
	},
	VNAV: {
		CUSTOM_VNAV_CLIMB_ENABLED: 'B748H_VNAV_CUSTOM_CLIMB_ENABLED'
	},

	SIM_RATE_MANAGER: {
		ACTIVATED: 'B748H_SIM_RATE_MANAGER_ACTIVATED'
	}
}
